company/urls.py
from django.urls import path
from company import views

urlpatterns = [
    path('login/', views.company_login, name='company_login'),
    path('logout/', views.company_logout, name='company_logout'),
    path('home/', views.company_home, name='company_home'),
    path('post-job/', views.post_job, name='post_job'),
    path('view-applications/<int:job_id>/', views.view_applications, name='view_applications'),
    path('delete-job/<int:job_id>/', views.delete_job, name='delete_job'),
     path('student-details/<int:student_id>/', views.student_details, name='student_details'),
    path('update-application-status/<int:application_id>/<str:status>/', views.update_application_status, name='update_application_status'),
    # Add more URLs for other views
]

stdplacement/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from django.urls import re_path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('home/',include('register.urls')),
    path('student/',include('std_app.urls')),
    path('company/',include('company.urls')),
    path('csv/',include('student_import.urls')),
]

# Serve media files in production
if not settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    ]
else:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student_import/urls.py
from django.urls import path
from . import views

app_name = 'student_import'
urlpatterns = [
    path('login/', views.login_view, name='csvlogin'),
    path('student-list/', views.student_list_view, name='student_list'),
    path('csv-import/', views.csv_import_view, name='csv_import'), 
    path('logout/', views.logout_view, name='csvlogout'),
]

student_import/models.py
from django.db import models

# Create your models here.

student_import/views.py
from django.contrib.auth import authenticate, login,logout
from django.shortcuts import render, redirect
from register.models import Student
from django.contrib.auth.decorators import login_required
from django.contrib import messages
import csv
from django.contrib.auth.models import User
from django.utils.datastructures import MultiValueDictKeyError


def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None and user.is_superuser:
            login(request, user)
            return redirect('student_import:student_list')
        else:
            error_message = 'Invalid username or password.'
            return render(request, 'student_import/login.html', {'error_message': error_message})

    return render(request, 'student_import/login.html')


def logout_view(request):
    logout(request)
    return redirect('student_import:csvlogin')

def student_list_view(request):
    students = Student.objects.all().order_by('-id')  # Order by the 'id' field in descending order
    return render(request, 'student_import/student_list.html', {'students': students})


@login_required
def csv_import_view(request):
    if request.method == 'POST':
        try:
            csv_file = request.FILES['csv_file']
            decoded_file = csv_file.read().decode('utf-8')
            csv_data = csv.reader(decoded_file.splitlines(), delimiter=',')

            # Skip the header row
            next(csv_data)

            for row in csv_data:
                username = row[0]
                password = row[1]
                first_name = row[2]
                last_name = row[3]
                branch = row[4]
                admission_no = row[5]
                std_email = row[6]

                # Create a new user
                user = User.objects.create_user(username=username, password=password, first_name=first_name,
                                                last_name=last_name)

                # Create a new student linked to the user
                student = Student(user=user, branch=branch, admission_no=admission_no, StdEmail=std_email)
                student.save()

            messages.success(request, 'Students imported successfully.')
            return redirect('student_import:student_list')
        except Exception as e:
            messages.error(request, f'Error importing CSV file: {str(e)}')
            return redirect('student_import:csv_import')

    return render(request, 'student_import/csv_import.html')

templates/student_import/csv_import.html
<!DOCTYPE html>
<html>
<head>
    <title>CSV Import</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #333;
            padding: 20px;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        
        .container {
            max-width: 600px;
            background-color: #f5f5f5;
            border-radius: 10px;
            padding: 40px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
            text-align: center;
        }
        
        h1 {
            color: #333;
            font-size: 28px;
            margin-bottom: 30px;
        }
        
        .messages {
            list-style: none;
            padding: 0;
            margin-bottom: 20px;
        }
        
        .messages li {
            padding: 10px;
            margin-bottom: 10px;
            border-radius: 5px;
        }
        
        .messages li.success {
            background-color: #dff0d8;
            color: #3c763d;
        }
        
        .messages li.error {
            background-color: #f2dede;
            color: #a94442;
        }
        
        form {
            margin-bottom: 30px;
        }
        
        label {
            display: block;
            font-weight: bold;
            margin-bottom: 10px;
        }
        
        input[type="file"] {
            margin-bottom: 10px;
        }
        
        button[type="submit"] {
            padding: 12px 24px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }
        
        button[type="submit"]:hover {
            background-color: #0056b3;
        }
        
        a {
            color: black;
            text-decoration: none;
            background-color: grey;
            padding: 10px 20px;
            border-radius: 5px;
            transition: background-color 0.3s ease;
        }
        
        a:hover {
            background-color: #ddd;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>CSV Import</h1>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="csv_file">Select CSV file:</label>
            <input type="file" id="csv_file" name="csv_file">
            <br>
            <button type="submit">Import</button>
        </form>
        <br>
        <a href="{% url 'student_import:student_list' %}">Back to Student List</a>
    </div>
</body>
</html>

templates/student_import/login.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: darkslategray;
            margin: 0;
            padding: 0;
        }

        .container {
            position: relative;
            max-width: 400px;
            margin: 0 auto;
            padding: 40px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            border-radius: 50px;
            text-align: center;
            margin-top: 8vh;
        }

        .logo {
            margin-bottom: 20px;
        }

        h1 {
            margin-bottom: 20px;
            color: #333;
        }

        p {
            margin-bottom: 20px;
            color: #777;
        }

        form {
            text-align: left;
        }

        label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
            color: #555;
        }

        input[type="text"],
        input[type="password"] {
            width: 100%;
            padding: 10px;
            border: none;
            border-radius: 30px;
            margin-bottom: 10px;
            outline: none;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.3);
            transition: box-shadow 0.3s;
        }

        input[type="text"]::-webkit-input-placeholder,
        input[type="password"]::-webkit-input-placeholder {
            color: #999;
        }

        input[type="text"]::-moz-placeholder,
        input[type="password"]::-moz-placeholder {
            color: #999;
        }

        input[type="text"]:-ms-input-placeholder,
        input[type="password"]:-ms-input-placeholder {
            color: #999;
        }

        input[type="text"]::placeholder,
        input[type="password"]::placeholder {
            color: #999;
        }

        input[type="text"]:focus,
        input[type="password"]:focus {
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
        }

        button[type="submit"] {
            background-color: #007bff;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
        }

        button[type="submit"]:hover {
            background-color: #0069d9;
        }
        
        .home-button {
            position: absolute;
            bottom: 5vh;
            right: 10px;
            background-color: #007bff;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            text-decoration: none;
            display: inline-block;
        }

        .home-button:hover {
            background-color: #0069d9;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="logo">
            <img src="{% static 'images/admin.jpg' %}" alt="Logo" width="300" height="270">
        </div>
        <h1>Admin Login</h1>
        {% if error_message %}
            <p>{{ error_message }}</p>
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" id="username" name="username" autocomplete="off">
            <br>
            <label for="password">Password:</label>
            <input type="password" id="password" name="password" autocomplete="off">
            <br>
            <button type="submit">Login</button>
        </form>
        <a href="{% url 'index' %}" class="home-button">Go to Home</a>
    </div>
</body>
</html>

templates/student_import/student_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Student List</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f5f5f5;
        }
        
        h1 {
            color: #333;
            font-size: 24px;
            text-align: center;
            padding: 20px 0;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            margin-bottom: 20px;
        }
        
        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        
        th {
            background-color: #f2f2f2;
        }
        
        .button-container {
            text-align: right;
            margin-bottom: 20px;
        }
        
        .button-container a {
            display: inline-block;
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            text-decoration: none;
            border-radius: 5px;
            margin-right: 10px;
        }
    </style>
</head>
<body>
    <div class="button-container">
        <a href="{% url 'student_import:csv_import' %}">Import CSV</a>
        <a href="{% url 'student_import:csvlogout' %}">Logout</a>
    </div>
    <h1>Student List</h1>
    <table>
        <thead>
            <tr>
                <th>User</th>
                <th>Branch</th>
                <th>Admission No</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            {% for student in students %}
            <tr>
                <td>{{ student.user }}</td>
                <td>{{ student.branch }}</td>
                <td>{{ student.admission_no }}</td>
                <td>{{ student.StdEmail }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>