company/urls.py
from django.urls import path
from company import views

urlpatterns = [
    path('login/', views.company_login, name='company_login'),
    path('logout/', views.company_logout, name='company_logout'),
    path('home/', views.company_home, name='company_home'),
    path('post-job/', views.post_job, name='post_job'),
    path('view-applications/<int:job_id>/', views.view_applications, name='view_applications'),
    path('delete-job/<int:job_id>/', views.delete_job, name='delete_job'),
     path('student-details/<int:student_id>/', views.student_details, name='student_details'),
    path('update-application-status/<int:application_id>/<str:status>/', views.update_application_status, name='update_application_status'),
    # Add more URLs for other views
]

stdplacement/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from django.urls import re_path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('home/',include('register.urls')),
    path('student/',include('std_app.urls')),
    path('company/',include('company.urls')),
    path('csv/',include('student_import.urls')),
]

# Serve media files in production
if not settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    ]
else:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

company/models.py
from django.db import models
from django.contrib.auth.models import User
from register.models import Student


class Company(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    image = models.FileField(upload_to='company_images', blank=True, null=True)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural="Company"

class Job(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    slots = models.IntegerField()
    role = models.CharField(max_length=30)
    cgpa = models.IntegerField()
    Backpaper = models.IntegerField()
    Lpa = models.IntegerField()
    internship = models.IntegerField()
    tech = models.CharField(max_length=30)
    City = models.CharField(max_length=20)
    Country = models.CharField(max_length=20)
    tenthper = models.IntegerField()
    twelthper = models.IntegerField()

    def __str__(self):
        return self.role


class JobApplication(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    STATUS_CHOICES=[
        ('ACCEPTED', 'Application Accepted'),
        ('REJECTED', 'Rejected'),
        ('ROUND2', 'Selected for 2nd Round'),
        ('ROUND3', 'Selected for 3rd Round'),
        ('ROUND_Final', 'Selected for Final Round'),
        ('PLACED', 'Congrats!You are Placed'),
        ('Remove', 'You Failed to Clear'),
    ]
    status = models.CharField(max_length=20, choices=STATUS_CHOICES,default='None')
    def __str__(self):
        return f"{self.student.user.username} applied for {self.job.role}"

templates/application_row.html
<!-- application_row.html -->
<tr>
    <td><a href="{% url 'student_details' application.student.id %}">{{ application.student.user.username }}</a></td>
    <td>{{ application.get_status_display }}</td>
    <td>
      {% if application.status != 'REJECTED' %}
        <a href="{% url 'update_application_status' application.id 'REJECTED' %}" style="background-color:red; border-radius: 5px; padding: 5px 10px; color: #fff;">Reject</a>
      {% endif %}
      {% if application.status == 'REJECTED' %}
        <a href="{% url 'update_application_status' application.id 'ACCEPTED' %}" style="background-color:green; border-radius: 5px; padding: 5px 10px; color: #fff;">Undo Rejection</a>
      {% endif %}
    </td>
    <td>
      <a href="{% url 'update_application_status' application.id 'ACCEPTED' %}" style="background-color:#FF5722; border-radius: 5px; padding: 5px 10px; color: #fff;">Accept</a>
    </td>
    <td>
      <a href="{% url 'update_application_status' application.id 'ROUND2' %}" style="background-color:#9C27B0; border-radius: 5px; padding: 5px 10px; color: #fff;">Round 2</a>
    </td>
    <td>
      <a href="{% url 'update_application_status' application.id 'ROUND3' %}" style="background-color:violet; border-radius: 5px; padding: 5px 10px; color: #fff;">Round 3</a>
    </td>
    <td>
      <a href="{% url 'update_application_status' application.id 'ROUND_Final' %}" style="background-color:grey;border-radius: 5px; padding: 5px 10px; color: #fff;">Final Round</a>
    </td>
    <td>
      <a href="{% url 'update_application_status' application.id 'PLACED' %}" style="background-color:black; border-radius: 5px; padding: 5px 10px; color: #fff;">PLACED</a>
    </td>
    <td><a href="{% url 'update_application_status' application.id 'Remove' %}" ><i class="fa fa-trash me-2"></i></a></td>
</tr>

templates/change_password.html
<!DOCTYPE html>
<html>
<head>
    <title>Change Password</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/css/bootstrap.min.css">
    <style>
        body {
            background-color: #514858;
            font-family: Arial, sans-serif;
        }

        .container {
            max-width: 60vw;
            margin-top:18vh;
            padding: 10vh;
            background-color: #fff;
            box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);
            border-radius: 20px;
            animation: glowing 3s infinite;
        }

        @keyframes glowing {
            0% {
                box-shadow: 0 0 5px #007bff;
            }
            50% {
                box-shadow: 0 0 20px #007bff;
            }
            100% {
                box-shadow: 0 0 5px #007bff;
            }
        }

        h1 {
            color: #333;
            font-size: 28px;
            font-weight: bold;
            text-align: center;
            margin-bottom: 30px;
        }

        form {
            margin-bottom: 20px;
        }

        .form-group {
            margin-bottom: 20px;
        }

        label {
            font-weight: bold;
        }

        .btn-primary {
            background-color: #007bff;
            border-color: #007bff;
        }

        .btn-primary:hover {
            background-color: #0069d9;
            border-color: #0062cc;
        }
        .back-button {
            text-align: right;
            margin-top: 10px;
        }

        .back-button a {
            text-decoration: none;
            color: #fff;
            font-size: 14px;
            font-weight: bold;
            background-color: #007bff;
            padding: 10px 20px;
            border-radius: 15px;
            display: inline-block;
        }

        .back-button a:hover {
            background-color: #0069d9;
            text-decoration: none;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Change Password</h1>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                {{ form.as_p }}
            </div>
            <div class="d-grid">
                <button type="submit" class="btn btn-primary">Change Password</button>
            </div>
            <div class="back-button">
                <a href="/home/student-home/">Back</a>
            </div>
        </form>
    </div>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/company_home.html
<!-- company_home.html -->

<!DOCTYPE html>
<html>
<head>
    <title>Welcome, {{ company.name }}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            background-color: #f8f9fa;
            font-family: Arial, sans-serif;
        }
        .content {
            width: 80%;
            margin: 0 auto;
            height:60%;
            padding: 10vh;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            /* Center the container */
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
        }
        .welcome-heading {
            font-size: 24px;
            font-weight: bold;
            color: #333;
            margin-bottom: 20px;
        }
        .job-list {
            list-style-type: none;
            padding: 0;
            margin: 0;
        }
        .job-item {
            margin-bottom: 20px;
            padding: 20px;
            background-color: #f1f1f1;
            border-radius: 8px;
        }
        .job-title {
            font-size: 18px;
            font-weight: bold;
            margin-bottom: 10px;
        }
        .job-details {
            font-size: 16px;
            margin-bottom: 10px;
        }
        .job-link {
            color: #007bff;
            text-decoration: none;
        }
        .job-link:hover {
            text-decoration: none;
        }
        .post-job-button {
            display: inline-block;
            background-color: #007bff;
            color: #fff;
            padding: 8px 16px;
            border-radius: 4px;
            text-decoration: none;
            font-weight: bold;
        }

        .logout-form {
            display: inline-block;
            margin-left: 10px;
        }
        .logout-button {
            background-color: #dc3545;
            color: #fff;
            padding: 8px 16px;
            border-radius: 4px;
            border: none;
            cursor: pointer;
        }
        .logout-button:hover {
            background-color: #c82333;
        }
        .company-image {
           margin-left:30vw;
            max-width: 15vw;
            margin-top:-8vw;
        }
    </style>
</head>
<body>
    <div class="content">
        <h2 class="welcome-heading">Welcome {{ company.name }}</h2>
        <img src="{{ company.image.url }}" alt="{{ company.name }} Image" class="company-image">
        <h3>Your Posted Jobs</h3>
        <ul class="job-list">
            {% for job in jobs %}
            <li class="job-item">
                <h4 class="job-title">{{ job.role }}</h4>
                <p class="job-details">
                    Slots: {{ job.slots }} | 
                    <a href="{% url 'view_applications' job.id %}" class="job-link">View Applications</a>
                    | <a href="{% url 'post_job' %}" class="job-link">Edit</a>
                    | <a href="{% url 'delete_job' job.id %}" class="job-link">Delete</a>
                </p>
            </li>
            {% endfor %}
        </ul>
        
        <a href="{% url 'post_job' %}" class="post-job-button">Post a Job</a>
        
        <!-- Logout Button -->
        <form action="{% url 'company_logout' %}" method="POST" class="logout-form">
            {% csrf_token %}
            <button type="submit" class="logout-button">Logout</button>
        </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/company_login.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <style>
	.nav-link{
		color: black;
	}
	body{
		background-color: #514858;
		font-family: 'Roboto', sans-serif;
	}
	.nav-link:hover{
		border-top: 1px solid #b62a5e;
		border-bottom: 1px solid #b62a5e; 
	}
	.form-control:hover{
		border: 1px solid #b62a5e;
	}
	.nav-item.active .nav-link {
		color: grey;
		border-top: 1px solid #b62a5e;
		border-bottom: 1px solid #b62a5e;
	}
    .login-container {
        margin-top: 1000px; /* Adjust the margin-top value as needed */
        padding: 40px;
        background-color: #fff;
        border-radius: 8px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }
        .login-heading {
            font-size: 24px;
            font-weight: bold;
            color: #333;
            margin-bottom: 20px;
        }
        .form-group {
            margin-bottom: 20px;
        }
        .form-group label {
            font-weight: bold;
        }
        .form-group input[type="text"],
        .form-group input[type="password"] {
            width: 100%;
            padding: 8px;
            border-radius: 4px;
            border: 1px solid #ccc;
            transition: border-color 0.3s ease-in-out, box-shadow 0.3s ease-in-out; /* Added box-shadow transition */
        }
    
        .form-group input[type="text"]:focus,
        .form-group input[type="password"]:focus {
            border-color: #007bff;
            box-shadow: 0 0 5px #007bff; /* Added box-shadow */
            outline: none;
        }
        .login-button {
            display: block;
            width: 100%;
            padding: 8px;
            background-color: #212529;
            color: #fff;
            border: none;
            border-radius: 10px;
            font-weight: bold;
            cursor: pointer;
            transition: background-color 0.3s ease-in-out;
        }
        .login-button:hover {
            background-color:orange;
        }
        .error-message {
            color: #dc3545;
            margin-top: 10px;
        }
        .card {
            border-radius: 30px; /* Added border-radius */
        }
        .loginnow{
            margin-top:10vh;
        }
</style>
</head>
<body>
  <nav class="navbar navbar-expand-lg " style="background-color: white; ">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">
            <img src="{% static 'images/logo.jpg' %}" alt="Logo" width="100" height="80">
          </a>
       <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end"  id="navbarSupportedContent">
        <ul class="navbar-nav mr-10 " style="font-weight: 500; font-size: 18px; float: right;">
          <li class="nav-item ">
            <a class="nav-link" style="padding-right:  20px;" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" style="padding-right:  20px;"href="/home/login/">Student Login</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" style="padding-right:  20px;"href="/company/login/">Company Login</a>
          </li>		
          <li class="nav-item">
            <a class="nav-link" style="padding-right:  20px;"href="/admin/login/?next=/admin/">Admin Login</a>
         </li>	
      				
        </ul>		  
     </div>
    </div>
  </nav>
	<section class="h-100" >
		<div class="container py-5 h-100">
		  <div class="row d-flex justify-content-center align-items-center h-100">
			<div class="col col-xl-10">
			  <div class="card" style="border-radius: 30px;">
				<div class="row g-0">
				  <div class="col-md-6 col-lg-5 d-none d-md-block">
					<img src="{% static 'images/company_login.png' %}"
					  alt="login form" class="img-fluid h-100" style="border-radius: 1rem 0 0 1rem;" />
				  </div>
				  <div class="col-md-6 col-lg-7 d-flex align-items-center loginnow">
					<div class="card-body p-4 p-lg-5 text-black">
	                 
                        <form method="POST" autocomplete="off">
                            {% csrf_token %}
                            
                            <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;font-size:30px; text-align: center;">Login into your Company account</h5>
                            <div class="form-group">
                                <label for="username">Username:</label>
                                <input type="text"  name="username" required>
                            </div>
                            <div class="form-group">
                                <label for="password">Password:</label>
                                <input type="password" name="password" required>
                            </div>
                            <button type="submit" class="login-button">Login</button>
                        </form>
                
                        {% if error_message %}
                            <p class="error-message">{{ error_message }}</p>
                        {% endif %}
                    </div>
	  
					</div>
				  </div>
				</div>
			  </div>
			</div>
		  </div>
		</div>
		</section>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
</html>

templates/form_not_filled.html
<!DOCTYPE html>
<html>
<head>
  <title>Form Not Filled</title>
  <style>
    body {
      background-color: #333333;
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
      font-family: Arial, sans-serif;
    }

    .container {
      background-color: #222222;
      box-shadow: 0 0 20px rgba(0, 0, 0, 0.4);
      padding: 20px;
      text-align: center;
      border-radius: 10px;
      color: #ffffff;
    }

    .card-title {
      margin-bottom: 0;
      font-size: 24px;
    }

    .card-body p {
      margin-bottom: 10px;
      font-size: 16px;
    }

    .card-footer {
      text-align: center;
      margin-top: 20px;
    }

    .btn-secondary {
      color: #fff;
      background-color: #007bff;
      border-color: #007bff;
      font-size: 16px;
      padding: 10px 20px;
      text-decoration: none;
      border-radius: 5px;
      transition: background-color 0.3s ease;
    }

    .btn-secondary:hover {
      background-color: #111111;
    }

    a {
      color: #fff;
      text-decoration: none;
    }

    a:hover {
      text-decoration: underline;
    }
  </style>
</head>
<body>

  <div class="container">
    <h1>Form Not Filled</h1>
    <p>You need to fill out the Student Details form before applying for jobs.</p>
    <a href="{% url 'form_details' %}" class="btn btn-secondary">Go to Student Details Form</a>
  </div>

</body>
</html>

templates/post_job.html
<!DOCTYPE html>
<html>
<head>
    <title>Post a Job</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            background-color: #f8f9fa;
            font-family: Arial, sans-serif;
        }
        .content {
            max-width: 800px;
            margin: 0 auto;
            padding: 40px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        .form-heading {
            font-size: 24px;
            font-weight: bold;
            color: #333;
            margin-bottom: 20px;
        }
        .form-group {
            margin-bottom: 20px;
        }
        .form-label {
            font-weight: bold;
        }
        .form-control {
            padding: 8px;
            border-radius: 4px;
            border: 1px solid #ced4da;
            box-shadow: 0 0 4px rgba(0, 0, 0, 0.1);
            transition: border-color 0.3s ease-in-out, box-shadow 0.3s ease-in-out;
        }
        .form-control:focus {
            border-color: #80bdff;
            box-shadow: 0 0 8px rgba(0, 123, 255, 0.25);
            outline: none;
        }
        .submit-button {
            background-color: #007bff;
            color: #fff;
            padding: 8px 16px;
            border-radius: 4px;
            border: none;
            cursor: pointer;
            font-weight: bold;
        }
        .submit-button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="content">
        {% if form.instance.pk %}
            <h2 class="form-heading">Edit Job</h2>
        {% else %}
            <h2 class="form-heading">Post a Job</h2>
        {% endif %}

        <form method="POST" action="{% url 'post_job' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_slots" class="form-label">Slots:</label>
                <input type="text" name="slots" id="id_slots" class="form-control" autocomplete="off" required value="{{ form.slots.value }}"  oninput="validateNumberInput('id_slots')">
            </div>
            <div class="form-group">
                <label for="id_role" class="form-label">Role:</label>
                <input type="text" name="role" id="id_role" class="form-control" autocomplete="off" required value="{{ form.role.value }}">
            </div>
            <div class="form-group">
                <label for="id_cgpa" class="form-label">CGPA:</label>
                <input type="text" name="cgpa" id="id_cgpa" class="form-control" autocomplete="off" required value="{{ form.cgpa.value }}"  oninput="validateNumberInput('id_cgpa')">
            </div>
            <div class="form-group">
                <label for="id_Backpaper" class="form-label">Backpaper:</label>
                <input type="text" name="Backpaper" id="id_Backpaper" class="form-control" autocomplete="off" required value="{{ form.Backpaper.value }}" oninput="validateNumberInput('id_Backpaper')">
            </div>
            <div class="form-group">
                <label for="id_Lpa" class="form-label">LPA:</label>
                <input type="text" name="Lpa" id="id_Lpa" class="form-control" autocomplete="off" required value="{{ form.Lpa.value }}"  oninput="validateNumberInput('id_Lpa')">
            </div>
            <div class="form-group">
                <label for="id_internship" class="form-label">Internship:</label>
                <input type="text" name="internship" id="id_internship" class="form-control" autocomplete="off" required value="{{ form.internship.value }}"  oninput="validateNumberInput('id_internship')">
            </div>
            <div class="form-group">
                <label for="id_tech" class="form-label">Tech:</label>
                <input type="text" name="tech" id="id_tech" class="form-control" autocomplete="off" required value="{{ form.tech.value }}">
            </div>
            <div class="form-group">
                <label for="id_City" class="form-label">City:</label>
                <input type="text" name="City" id="id_City" class="form-control" autocomplete="off" required value="{{ form.City.value }}">
            </div>
            <div class="form-group">
                <label for="id_Country" class="form-label">Country:</label>
                <input type="text" name="Country" id="id_Country" class="form-control" autocomplete="off" required value="{{ form.Country.value }}">
            </div>
            <div class="form-group">
                <label for="id_tenthper" class="form-label">Tenth Percentage:</label>
                <input type="text" name="tenthper" id="id_tenthper" class="form-control" autocomplete="off" required value="{{ form.tenthper.value }}" oninput="validatePercentageInput('id_tenthper')">
            </div>
            <div class="form-group">
                <label for="id_twelthper" class="form-label">Twelth Percentage:</label>
                <input type="text" name="twelthper" id="id_twelthper" class="form-control" autocomplete="off" required value="{{ form.twelthper.value }}" oninput="validatePercentageInput('id_twelthper')">
            </div>
            <button type="submit" class="submit-button">Save</button>
        </form>
    </div>
        <script>
            function validateNumberInput(inputId) {
                const input = document.getElementById(inputId);
                const value = input.value;
                const isNumber = /^[0-9]*$/.test(value);
    
                if (!isNumber) {
                    alert("Please enter a valid number.");
                    input.value = '';
                }
            }
        </script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/student_details.html
<!DOCTYPE html>
<html>
<head>
  <title>Student Details</title>
  <style>
    body {
      background-color: #333;
      font-family: Arial, sans-serif;
      display: flex;
      align-items: center;
      justify-content: center;
      min-height: 100vh;
      padding: 20px;
    }

.container {
  max-width: 400px;
  background-color: #1a1a1a;
  border-radius: 10px;
  box-shadow: 0 0 20px rgba(0, 0, 0, 0.4);
  padding: 20px;
  text-align: center;
}

h1 {
  color: #fff;
  margin-bottom: 20px;
}

h2 {
  color: #fff;
  margin-bottom: 10px;
}

img {
  display: block;
  margin: 0 auto;
  width: 250px;
  height: 170px;
  border-radius: 10px;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.4);
  margin-bottom: 20px;
}

p {
  color: #fff;
  margin-bottom: 10px;
}
  </style>
</head>
<body>
  <div class="container">
    <img src="{{ student.image.url }}" alt="Student Image">
    <h2>{{ student.user.first_name }} {{student.user.last_name}}</h2>
    <p>Branch: {{ student.branch }}</p>
    <p>Admission No: {{ student.admission_no }}</p>
    <p>Personal Email: {{ student_details.PEmailId }}</p>
    <p>Current CGPA: {{ student_details.Current_CGPA }}</p>
    <p>Supply Count: {{ student_details.Supply_Count }}</p>
    <p>Internships Done: {{ student_details.Internship }}</p>
    <p>LinkedIn: {{ student_details.LinkedIn }}</p>
    <!-- Display more student details as needed -->
  </div>
</body>
</html>

templates/update_profile_image.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Profile Image</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            background-color: darkslategrey;
            font-family: Arial, sans-serif;
        }

        .container {
            max-width: 40vw;
            margin-top: 12vw;
            padding: 40px;
            background-color: #ffffff;
            border-radius: 20px;
            box-shadow: 0px 0px 20px rgba(0, 0, 0, 0.1);
            animation: glowing 3s infinite;
            text-align: center;
        }

        @keyframes glowing {
            0% {
                box-shadow: 0 0 5px #007bff;
            }
            50% {
                box-shadow: 0 0 20px #007bff;
            }
            100% {
                box-shadow: 0 0 5px #007bff;
            }
        }

        h2 {
            margin-bottom: 30px;
            color: #333;
            font-size: 24px;
        }

        form {
            margin-top: 20px;
        }

        .form-group {
            margin-bottom: 20px;
        }

        label {
            font-weight: bold;
        }

        button[type="submit"] {
            background-color: #b62a5e;
            border-color: #b62a5e;
            color: #fff;
            padding: 8px 20px;
            font-weight: bold;
            border-radius: 20px;
        }

        button[type="submit"]:hover {
            background-color: #a61f51;
            border-color: #a61f51;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Update Profile Image</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/js/bootstrap.bundle.min.js"></script>
</body>
</html>